# Generated by Django 4.2.30 on 2026-07-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0005_profile_about_me_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Show a verified badge next to this profile.'),
        ),
    ]
