# Generated by Django 4.2.30 on 2026-07-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accent_theme',
            field=models.CharField(choices=[('purple', 'Purple'), ('cyan', 'Cyan'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('rose', 'Rose')], default='purple', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_lightwave_super',
            field=models.BooleanField(default=False, help_text='Show Lightwave Super early-access status.'),
        ),
        migrations.AlterField(
            model_name='dweet',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
