# Generated by Django 4.2.30 on 2026-07-19 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0003_extra_reply_dweetlike_dweetdislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
