# Generated by Django 4.2.30 on 2026-07-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0004_alter_dweet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
